MAPPING = {
    "Exchange": "exchange",
    "SharePoint": "sharepoint",
    "OneDrive": "onedrive",
    "DropBox": "dropbox",
    "Box": "box",
    "Google Drive": "googledrive",
    "Gmail": "gmail",
    "Teams": "teams",
    "Exchange Server": "exchangeserver",
    "Salesforce Sandbox": "salesforce_sandbox",
    "Salesforce Production": "salesforce_production",
    "Teams Chat": "teams_chat",
    "Security Risk": "securityrisk",
    "Virtual Analyzer": "virtualanalyzer",
    "Ransomware": "ransomware",
    "DLP": "dlp",
    "Account Disable": "ACCOUNT_DISABLE",
    "Account Enable MFA": "ACCOUNT_ENABLE_MFA",
    "Account Reset Password": "ACCOUNT_RESET_PASSWORD",
    "Account Revoke Signin Sessions": "ACCOUNT_REVOKE_SIGNIN_SESSIONS",
    "Mail Delete": "MAIL_DELETE",
    "Mail Quarantine": "MAIL_QUARANTINE",
    "Mail Restore": "MAIL_RESTORE"
}
